"""Live-like paper broker for liquidation-lane calibration.

The broker here simulates the order/fill boundary only. Signal generation,
regime routing, and risk checks stay deterministic so paper results can be
compared to backtests without introducing exchange side effects.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from typing import Iterable


def _price_at_return(entry: float, direction: str, return_pct: float) -> float:
    if direction == "long":
        return entry * (1.0 + return_pct / 100.0)
    return entry * (1.0 - return_pct / 100.0)


def _return_pct(direction: str, entry: float, exit_price: float) -> float:
    if entry <= 0:
        return 0.0
    if direction == "long":
        return (exit_price - entry) / entry * 100.0
    if direction == "short":
        return (entry - exit_price) / entry * 100.0
    return 0.0


def _ts_from_bar(bar: dict) -> str:
    payload = bar.get("payload", {}) if isinstance(bar.get("payload"), dict) else {}
    t = bar.get("t", payload.get("t"))
    try:
        return datetime.fromtimestamp(int(t) / 1000, tz=timezone.utc).isoformat()
    except (TypeError, ValueError):
        return ""


def _float_from_bar(bar: dict, key: str) -> float | None:
    payload = bar.get("payload", {}) if isinstance(bar.get("payload"), dict) else {}
    try:
        return float(bar.get(key, payload.get(key)))
    except (TypeError, ValueError):
        return None


@dataclass(frozen=True)
class PaperBracket:
    """A simulated bracket or trailing-exit intent."""

    entry_price: float
    initial_stop_price: float
    target_price: float | None
    activation_price: float | None
    trail_bps: float | None
    max_hold_minutes: int
    stop_slippage_bps: float
    round_trip_cost_bps: float

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class PaperPosition:
    """A paper position generated by the deterministic strategy router."""

    paper_id: str
    paper_scope: str
    cascade_key: str
    symbol: str
    side: str
    lane: str
    direction: str
    event_ts: str
    entry_ts: str
    entry_idx: int
    entry_price: float
    notional_usd: float
    risk_usd: float
    bracket: PaperBracket
    metadata: dict

    def to_dict(self) -> dict:
        out = asdict(self)
        out["bracket"] = self.bracket.to_dict()
        return out


@dataclass(frozen=True)
class PaperFill:
    """Current simulated state of a paper position."""

    paper_id: str
    status: str
    exit_ts: str | None
    exit_price: float | None
    exit_reason: str | None
    gross_return_pct: float
    net_return_pct: float
    pnl_usd: float
    r_multiple: float
    mae_pct: float
    mfe_pct: float
    bars_held: int
    final_trailing_stop: float | None

    def to_dict(self) -> dict:
        return asdict(self)


def _excursions_pct(direction: str, entry: float, high: float, low: float) -> tuple[float, float]:
    if direction == "long":
        favorable = (high - entry) / entry * 100.0
        adverse = (entry - low) / entry * 100.0
    else:
        favorable = (entry - low) / entry * 100.0
        adverse = (high - entry) / entry * 100.0
    return max(0.0, favorable), max(0.0, adverse)


def mark_position(position: PaperPosition, candles: Iterable[dict]) -> PaperFill:
    """Mark a paper position using completed candles after its entry.

    Stops win over targets on the same bar. Stop exits include an extra
    slippage haircut; target and trailing exits pay only configured costs.
    """
    ordered = list(candles)
    if position.entry_idx >= len(ordered):
        return _open_fill(position, 0.0, 0.0, None, None, None, None)

    bracket = position.bracket
    direction = position.direction
    entry = position.entry_price
    risk_pct = abs(_return_pct(direction, entry, bracket.initial_stop_price))
    last_idx = min(position.entry_idx + bracket.max_hold_minutes, len(ordered) - 1)
    if last_idx <= position.entry_idx:
        mark_price = _float_from_bar(ordered[position.entry_idx], "c")
        return _open_fill(position, 0.0, 0.0, trailing_stop, mark_price, ordered[position.entry_idx], position.entry_idx)

    active_trail = False
    best_price = entry
    trailing_stop = bracket.initial_stop_price
    mae_pct = 0.0
    mfe_pct = 0.0

    for idx in range(position.entry_idx + 1, last_idx + 1):
        bar = ordered[idx]
        high = _float_from_bar(bar, "h")
        low = _float_from_bar(bar, "l")
        close = _float_from_bar(bar, "c")
        if high is None or low is None or close is None:
            continue
        favorable, adverse = _excursions_pct(direction, entry, high, low)
        mfe_pct = max(mfe_pct, favorable)
        mae_pct = max(mae_pct, adverse)

        if direction == "long":
            if low <= bracket.initial_stop_price and not active_trail:
                    return _closed_fill(
                        position, ordered, idx, "initial_stop", bracket.initial_stop_price, mae_pct, mfe_pct, trailing_stop
                    )
            if bracket.activation_price is not None and high >= bracket.activation_price:
                active_trail = True
            if active_trail and bracket.trail_bps is not None:
                best_price = max(best_price, high)
                trailing_stop = max(
                    bracket.initial_stop_price,
                    best_price * (1.0 - bracket.trail_bps / 10_000.0),
                )
                if low <= trailing_stop:
                    return _closed_fill(position, ordered, idx, "trailing_stop", trailing_stop, mae_pct, mfe_pct, trailing_stop)
            if bracket.target_price is not None and high >= bracket.target_price:
                return _closed_fill(position, ordered, idx, "target", bracket.target_price, mae_pct, mfe_pct, trailing_stop)
        else:
            if high >= bracket.initial_stop_price and not active_trail:
                return _closed_fill(
                    position, ordered, idx, "initial_stop", bracket.initial_stop_price, mae_pct, mfe_pct, trailing_stop
                )
            if bracket.activation_price is not None and low <= bracket.activation_price:
                active_trail = True
            if active_trail and bracket.trail_bps is not None:
                best_price = min(best_price, low)
                trailing_stop = min(
                    bracket.initial_stop_price,
                    best_price * (1.0 + bracket.trail_bps / 10_000.0),
                )
                if high >= trailing_stop:
                    return _closed_fill(position, ordered, idx, "trailing_stop", trailing_stop, mae_pct, mfe_pct, trailing_stop)
            if bracket.target_price is not None and low <= bracket.target_price:
                return _closed_fill(position, ordered, idx, "target", bracket.target_price, mae_pct, mfe_pct, trailing_stop)

    if len(ordered) - 1 < position.entry_idx + bracket.max_hold_minutes:
        mark_price = _float_from_bar(ordered[-1], "c") if ordered else None
        mark_bar = ordered[-1] if ordered else None
        return _open_fill(position, mae_pct, mfe_pct, trailing_stop, mark_price, mark_bar, len(ordered) - 1)
    close = _float_from_bar(ordered[last_idx], "c")
    if close is None:
        return _open_fill(position, mae_pct, mfe_pct, trailing_stop, None, None, last_idx)
    reason = "timeout_trailing_active" if active_trail else "timeout_no_activation"
    return _closed_fill(position, ordered, last_idx, reason, close, mae_pct, mfe_pct, trailing_stop)


def _open_fill(
    position: PaperPosition,
    mae_pct: float,
    mfe_pct: float,
    trailing_stop: float | None,
    mark_price: float | None,
    mark_bar: dict | None,
    mark_idx: int | None,
) -> PaperFill:
    gross = _return_pct(position.direction, position.entry_price, mark_price) if mark_price is not None else 0.0
    net = gross - (position.bracket.round_trip_cost_bps / 100.0) if mark_price is not None else 0.0
    risk_pct = abs(_return_pct(position.direction, position.entry_price, position.bracket.initial_stop_price))
    return PaperFill(
        paper_id=position.paper_id,
        status="open",
        exit_ts=_ts_from_bar(mark_bar) if mark_bar is not None else None,
        exit_price=round(mark_price, 8) if mark_price is not None else None,
        exit_reason=None,
        gross_return_pct=round(gross, 4),
        net_return_pct=round(net, 4),
        pnl_usd=round(position.notional_usd * net / 100.0, 4),
        r_multiple=round(net / risk_pct, 4) if risk_pct > 0 else 0.0,
        mae_pct=round(mae_pct, 4),
        mfe_pct=round(mfe_pct, 4),
        bars_held=max(0, mark_idx - position.entry_idx) if mark_idx is not None else 0,
        final_trailing_stop=round(trailing_stop, 8) if trailing_stop is not None else None,
    )


def _closed_fill(
    position: PaperPosition,
    candles: list[dict],
    exit_idx: int,
    exit_reason: str,
    raw_exit_price: float,
    mae_pct: float,
    mfe_pct: float,
    trailing_stop: float | None,
) -> PaperFill:
    stop_like = exit_reason == "initial_stop"
    slip = position.bracket.stop_slippage_bps / 10_000.0 if stop_like else 0.0
    if stop_like and position.direction == "long":
        exit_price = raw_exit_price * (1.0 - slip)
    elif stop_like:
        exit_price = raw_exit_price * (1.0 + slip)
    else:
        exit_price = raw_exit_price
    gross = _return_pct(position.direction, position.entry_price, exit_price)
    net = gross - (position.bracket.round_trip_cost_bps / 100.0)
    risk_pct = abs(_return_pct(position.direction, position.entry_price, position.bracket.initial_stop_price))
    return PaperFill(
        paper_id=position.paper_id,
        status="closed",
        exit_ts=_ts_from_bar(candles[exit_idx]),
        exit_price=round(exit_price, 8),
        exit_reason=exit_reason,
        gross_return_pct=round(gross, 4),
        net_return_pct=round(net, 4),
        pnl_usd=round(position.notional_usd * net / 100.0, 4),
        r_multiple=round(net / risk_pct, 4) if risk_pct > 0 else 0.0,
        mae_pct=round(mae_pct, 4),
        mfe_pct=round(mfe_pct, 4),
        bars_held=max(0, exit_idx - position.entry_idx),
        final_trailing_stop=round(trailing_stop, 8) if trailing_stop is not None else None,
    )
