"""
paper_funding_neg_fade.py

Live paper-trader for the `funding_neg_fade` strategy on Hyperliquid.

Per user profile (2026-08-03):
  - Position size = max account risk / stop distance
  - Stop level = observed MAE (max adverse excursion)
  - TP = observed MFE * R multiple

Per-symbol risk parameters derived from
  data/strategy_search/detail_funding_neg_fade.json (regenerated by
  backtest_funding_neg_fade_detail.py on every run).

Bankroll: $1,000 USDC. Risk per trade: 1% = $10. 10x leverage cap.

Modes:
  --mode analyze    : Run the detailed backtest per symbol, print per-symbol stats
  --mode paper      : Walk funding panel, append paper positions to JSONL
  --mode audit      : Read the JSONL positions file, compute live metrics

Output: data/paper_funding_neg_fade_positions.jsonl
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass, asdict, field
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))
# src/ too, so the exchange modes can import OrderManager when this is
# run as a script from scripts/ rather than as a package.
sys.path.insert(0, str(PROJECT_ROOT))

from strategy_search import signal_funding_neg_fade, load_hl_with_funding  # type: ignore


# -----------------------------------------------------------------------------
# Per-asset policy
# -----------------------------------------------------------------------------

V1_SYMBOLS = ["BTC", "ETH", "HYPE"]
RESEARCH_SYMBOLS = [
    "SOL",
    "xyz:GOLD", "xyz:SILVER", "xyz:NVDA", "xyz:MSFT",
    "xyz:SP500", "xyz:CL", "xyz:MU", "xyz:MSTR",
    "xyz:BRENTOIL", "xyz:COIN", "xyz:GOOGL",
]
ALL_SYMBOLS = V1_SYMBOLS + RESEARCH_SYMBOLS

# Per-symbol risk policy (overridable via config)
# stop_pct = observed MAE p10 (conservative sizing)
# tp_pct = MFE p50 * R_MULTIPLE
# max_hold_h = observed hold p50
# R multiple for TP sizing
R_MULTIPLE = 1.5

# Per-asset profile from detail backtest (regenerated by backtest_funding_neg_fade_detail.py)
# Numbers from 2026-08-18 sweep (17 days of HL live data, 1h bars, TP=1% SL=1% max_hold=24h)
# Recalibrated 2026-08-26 on 7 months of venue-aligned data (5,002h/symbol,
# n=87-111 per symbol) instead of the 25 days the old values came from.
#
# Two changes, both required -- either alone leaves the lane under the gate:
#   hold 4h -> 24h   the 2-8h band is the worst on Hyperliquid (measured across
#                    349 profitable traders: 53% winners, median PF 1.33, vs
#                    74%/2.63 at 24-72h)
#   stops x3         the old stops were tuned on 25 days and were being hit by
#                    noise; every width x1.0 config loses (PF 0.86-0.92)
#
# Verified on independent halves rather than one window:
#   HYPE  Jan-Apr PF 1.87 (n=43)   May-Aug PF 1.56 (n=44)
#   ETH   Jan-Apr PF 1.68 (n=55)   May-Aug PF 1.59 (n=33)
#   BTC   1.05 / 0.87  and  SOL  0.98 / 0.88  -- dead in BOTH halves, removed.
#
# BTC and SOL are deliberately absent: the loop skips uncalibrated symbols, so
# dropping them here stops the lane trading them at all.
PER_ASSET_POLICY = {
    "ETH":  {"bucket": "v1", "stop_pct": 0.0279, "tp_pct": 0.0276, "max_hold_h": 24},
    "HYPE": {"bucket": "v1", "stop_pct": 0.0381, "tp_pct": 0.0516, "max_hold_h": 24},
}

# Strategy params
NEG_THRESHOLD = -5e-6
COST_BPS_ROUND_TRIP = 8.0  # 4bps per side

# Bankroll
BANKROLL = 1_000.0
RISK_PER_TRADE_PCT = 0.01  # 1% = $10
RISK_PER_TRADE_USD = BANKROLL * RISK_PER_TRADE_PCT

# Risk circuit breakers
DAILY_LOSS_LIMIT_PCT = 0.03  # 3% = $30
CONSEC_LOSS_HALT = 3  # 3 consecutive losses → halt 24h

# Output paths
POSITIONS_PATH = PROJECT_ROOT / "data" / "paper_funding_neg_fade_positions.jsonl"
DETAIL_PATH = PROJECT_ROOT / "data" / "strategy_search" / "detail_funding_neg_fade.json"

# -----------------------------------------------------------------------------
# Live-trading mode (Step 4 of fast-path, 2026-08-21)
# -----------------------------------------------------------------------------
# Staged but OFF by default. To enable:
#   1. User deposits $50 USDC mainnet to API wallet via HL UI (Step 3)
#   2. Mavis flips LIVE_TRADING_ENABLED = True (one-line edit, no flag)
#   3. Next :05 cron tick starts placing real HYPE bracket orders
# The testnet bracket proof (data/testnet_proof_status.json) must exist
# with status == "bracket_proof_passed" or this mode refuses to start.
LIVE_TRADING_ENABLED = False  # SAFETY: explicit flip required
LIVE_SYMBOLS = ["HYPE"]        # HYPE-only at the live phase
LIVE_BANKROLL_USD = 50.0       # hard cap; $50 ramp
LIVE_RISK_USD = 0.50           # 1% of $50 = $0.50 per trade
LIVE_ORDERS_PATH = PROJECT_ROOT / "data" / "live_funding_neg_fade_orders.jsonl"
LIVE_POSITIONS_PATH = PROJECT_ROOT / "data" / "live_funding_neg_fade_positions.jsonl"
TESTNET_PROOF_PATH = PROJECT_ROOT / "data" / "testnet_proof_status.json"

# --- Testnet forward-execution -------------------------------------------
# The paper simulator invents a portfolio no exchange would grant: it walked
# each symbol independently, ignored max_open_positions, and read a funding
# rate the venue had not published yet. Routing the same signals to testnet
# replaces every one of those assumptions with an actual venue response --
# real fills, real rejects, real spread. No mainnet funds are at risk.
TESTNET_ORDERS_PATH = PROJECT_ROOT / "data" / "testnet_funding_neg_fade_orders.jsonl"
TESTNET_POSITIONS_PATH = PROJECT_ROOT / "data" / "testnet_funding_neg_fade_positions.jsonl"
TESTNET_STATE_PATH = PROJECT_ROOT / "data" / "testnet_funding_neg_fade_state.json"
TESTNET_OPEN_POSITIONS_PATH = PROJECT_ROOT / "data" / "testnet_open_positions.json"
TESTNET_SYMBOLS = ["HYPE", "SOL", "BTC", "ETH"]
TESTNET_BANKROLL_USD = 1000.0   # testnet faucet money; mirrors the $1k framework
TESTNET_RISK_USD = 10.0         # 1% of bankroll

# Concurrency cap, mirroring RiskConfig.max_open_positions. The simulator held
# four lanes at once for 11 hours; live would have rejected the fourth.
MAX_OPEN_POSITIONS = 3

# Safety infrastructure (added 2026-08-22 pre-live audit)
KILL_SWITCH_PATH = PROJECT_ROOT / "data" / "live_kill_switch.flag"
HEARTBEAT_PATH = PROJECT_ROOT / "data" / "live_heartbeat.txt"
LIVE_STATE_PATH = PROJECT_ROOT / "data" / "live_funding_neg_fade_state.json"
LIVE_OPEN_POSITIONS_PATH = PROJECT_ROOT / "data" / "live_open_positions.json"
LIVE_CIRCUIT_LOG_PATH = PROJECT_ROOT / "data" / "live_circuit_log.jsonl"
# When this many consecutive losses are detected across ticks, the live mode
# refuses to open new orders until the user resets the state or until 24h pass.
LIVE_CONSEC_LOSS_HALT = 3
# When bankroll drawdown from LIVE_BANKROLL_USD exceeds this fraction,
# live mode refuses new orders (hard kill).
LIVE_DRAWDOWN_KILL_PCT = 0.40


# -----------------------------------------------------------------------------
# Per-trade paper position record
# -----------------------------------------------------------------------------

@dataclass
class PaperPosition:
    symbol: str
    bucket: str  # "v1" or "research"
    side: str  # "long"
    entry_ts: str
    entry_price: float
    entry_funding: float
    notional_usd: float
    stop_pct: float
    tp_pct: float
    max_hold_h: int
    risk_usd: float
    decision_id: str  # 128-bit hex
    paper_id: str
    status: str = "open"  # open / closed
    exit_ts: str = ""
    exit_price: float = 0.0
    exit_reason: str = ""  # tp / sl / max_hold
    mae_pct: float = 0.0
    mfe_pct: float = 0.0
    hold_bars: int = 0
    funding_collected_usd: float = 0.0
    price_pnl_usd: float = 0.0
    cost_usd: float = 0.0
    net_pnl_usd: float = 0.0
    cum_pnl_usd: float = 0.0
    notes: str = ""


def paper_trade_id(symbol: str, entry_ts) -> str:
    """Stable identity for a simulated trade: symbol + entry bar.

    Paper mode re-walks the entire panel on every run, so this MUST NOT
    contain a random component. When it did, each run minted a fresh id for a
    trade already on disk, paper_id_exists() never matched, and the same
    simulated trade was appended once per run -- silently inflating the n that
    the graduation gates are scored on.
    """
    return f"paper-fnf-{symbol}-{entry_ts.strftime('%Y%m%d%H%M')}"


def gen_id() -> str:
    import secrets
    return "0x" + secrets.token_hex(16)


# -----------------------------------------------------------------------------
# Mode: analyze — re-run detail backtest
# -----------------------------------------------------------------------------

def mode_analyze() -> None:
    """Re-run the detail backtest and print per-symbol observed stats.
    Updates PER_ASSET_POLICY based on observed MAE p10 and MFE p50 * R."""
    print(f"=== analyze: detailed funding_neg_fade backtest (1%/1% TP/SL, max_hold=24h) ===\n")
    updated_policy = {}
    for sym in ALL_SYMBOLS:
        try:
            df, label = load_hl_with_funding(sym)
        except Exception as e:
            print(f"  {sym}: FAILED to load: {e}")
            continue
        n_neg_fund = int((df["funding_actual"] < NEG_THRESHOLD).sum())
        # Use the detail backtest
        from backtest_funding_neg_fade_detail import detailed_backtest, score_detail  # type: ignore
        trades = detailed_backtest(df)
        s = score_detail(trades)
        if not s:
            print(f"  {sym}: no trades")
            continue
        # Per user profile: stop from observed MAE (use p10 for conservative), TP from MFE * R
        # Use med MAE (less conservative) for sizing the typical case
        new_stop = max(0.005, abs(s["mae_p10"]) / 100)  # p10 MAE (percent -> fraction)
        new_tp = min(0.03, (s["mfe_p50"] / 100) * R_MULTIPLE)  # MFE p50 * R, capped at 3%
        new_hold = max(1, int(s["hold_med"]))
        prev = PER_ASSET_POLICY[sym]
        updated_policy[sym] = {
            "bucket": prev["bucket"],
            "stop_pct": round(new_stop, 4),
            "tp_pct": round(new_tp, 4),
            "max_hold_h": new_hold,
            "obs_n": s["n"],
            "obs_pf": round(s["pf"], 2),
            "obs_wr": round(s["wr"], 1),
            "obs_med_pct": round(s["med"], 4),
            "obs_mae_p10": round(s["mae_p10"], 4),
            "obs_mfe_p50": round(s["mfe_p50"], 4),
        }
        print(f"--- {sym} ---")
        print(f"  n={s['n']} WR={s['wr']:.1f}% PF={s['pf']:.2f} med={s['med']:+.4f}% net={s['net_pct_total']:+.4f}%")
        print(f"  observed MAE: med={s['mae_med']:.4f}% p10={s['mae_p10']:.4f}% worst={s['mae_worst']:.4f}%")
        print(f"  observed MFE: med={s['mfe_p50']:.4f}% p90={s['mfe_p90']:.4f}% max={s['mfe_max']:.4f}%")
        print(f"  observed hold: med={s['hold_med']:.0f}h p90={s['hold_p90']:.0f}h")
        print(f"  -> proposed stop={new_stop:.4f}  tp={new_tp:.4f}  max_hold={new_hold}h")
        print()

    if updated_policy:
        # Write policy update
        pol_path = PROJECT_ROOT / "data" / "strategy_search" / "paper_funding_neg_fade_policy.json"
        pol_path.write_text(json.dumps(updated_policy, indent=2, default=str))
        print(f"policy updated -> {pol_path}")


# -----------------------------------------------------------------------------
# Mode: paper — walk panel, open/close paper positions
# -----------------------------------------------------------------------------

def load_existing_positions() -> list[dict]:
    if not POSITIONS_PATH.exists():
        return []
    out = []
    with POSITIONS_PATH.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return out


def append_position(pos: dict) -> None:
    with POSITIONS_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(pos, default=str) + "\n")


# -----------------------------------------------------------------------------
# State tracking for live mode
# -----------------------------------------------------------------------------

STATE_PATH = PROJECT_ROOT / "data" / "paper_funding_neg_fade_state.json"


def load_state() -> dict:
    if not STATE_PATH.exists():
        return {"last_processed_ts": {}, "open_positions": {}}
    try:
        return json.loads(STATE_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {"last_processed_ts": {}, "open_positions": {}}


def save_state(state: dict) -> None:
    tmp = STATE_PATH.with_suffix(".tmp")
    tmp.write_text(json.dumps(state, indent=2, default=str), encoding="utf-8")
    tmp.replace(STATE_PATH)


def paper_id_exists(paper_id: str) -> bool:
    """Check if paper_id already exists in JSONL (for idempotency)."""
    if not POSITIONS_PATH.exists():
        return False
    with POSITIONS_PATH.open("r", encoding="utf-8") as f:
        for line in f:
            if paper_id in line:
                return True
    return False


def _close_position(
    pos: PaperPosition,
    exit_price: float,
    exit_reason: str,
    cur_mae: float,
    cur_mfe: float,
    hold_bars: int,
    funding_collected: float,
    cost_usd_per_trade: float,
    ts_iso: str,
    ts_date: str,
) -> tuple[float, bool]:
    """Close an open position, write to JSONL (idempotent on paper_id), return (net_pnl_usd, is_loss)."""
    # Idempotency: skip if this paper_id already has a record in JSONL
    if paper_id_exists(pos.paper_id):
        # Already closed in a prior run — return a fake zero P&L
        return 0.0, False

    price_pnl_usd = (exit_price - pos.entry_price) / pos.entry_price * pos.notional_usd
    net_pnl_usd = price_pnl_usd - cost_usd_per_trade + funding_collected

    pos.status = "closed"
    pos.exit_ts = ts_iso
    pos.exit_price = float(exit_price)
    pos.exit_reason = exit_reason
    pos.mae_pct = float(cur_mae * 100)
    pos.mfe_pct = float(cur_mfe * 100)
    pos.hold_bars = int(hold_bars)
    pos.funding_collected_usd = float(funding_collected)
    pos.price_pnl_usd = float(price_pnl_usd)
    pos.cost_usd = float(cost_usd_per_trade)
    pos.net_pnl_usd = float(net_pnl_usd)

    append_position(asdict(pos))
    return net_pnl_usd, net_pnl_usd < 0


def mode_paper(symbol_filter: list[str] | None = None) -> None:
    """Walk each symbol's funding panel, simulate paper trading."""
    syms = symbol_filter or ALL_SYMBOLS
    existing = load_existing_positions()
    existing_ids = {p.get("paper_id") for p in existing}
    cum_pnl = sum(p.get("net_pnl_usd", 0) for p in existing)
    daily_pnl: dict[str, float] = {}
    consec_loss = 0
    halt_until: dict[str, str] = {}  # sym -> halt_until_iso

    print(f"=== paper: walk funding panel ===")
    print(f"  bankroll: ${BANKROLL:.0f}  risk/trade: ${RISK_PER_TRADE_USD:.0f}  ({RISK_PER_TRADE_PCT*100:.0f}%)")
    print(f"  daily loss limit: ${BANKROLL*DAILY_LOSS_LIMIT_PCT:.0f}  consec halt: {CONSEC_LOSS_HALT}")
    print(f"  symbols: {syms}")
    print(f"  existing positions: {len(existing)}  cum_pnl: ${cum_pnl:+.2f}")
    print()

    for sym in syms:
        try:
            df, label = load_hl_with_funding(sym)
        except Exception as e:
            print(f"  {sym}: load failed: {e}")
            continue
        if sym not in PER_ASSET_POLICY:
            # No calibrated stop/tp for this symbol yet. Skip rather than
            # crash the whole run — ALL_SYMBOLS includes research names
            # that have never been calibrated, and an uncalibrated symbol
            # must not be paper-traded at a guessed size.
            print(f"  {sym}: no PER_ASSET_POLICY entry, skipping")
            continue
        policy = PER_ASSET_POLICY[sym]
        sig = signal_funding_neg_fade(df, funding_col="funding_actual", neg_threshold=NEG_THRESHOLD)
        closes = df["close"].values
        highs = df["high"].values
        lows = df["low"].values
        funds = df["funding_actual"].values
        times = df.index

        # Position sizing
        stop_pct = policy["stop_pct"]
        tp_pct = policy["tp_pct"]
        max_hold = policy["max_hold_h"]
        risk_usd = RISK_PER_TRADE_USD
        # notional = risk / stop
        notional_usd = min(risk_usd / stop_pct, BANKROLL * 10)  # 10x leverage cap
        # paper cost: round-trip
        cost_usd_per_trade = (COST_BPS_ROUND_TRIP / 10_000.0) * notional_usd

        # Walk
        in_trade = False
        pos: PaperPosition | None = None
        cur_mae = 0.0
        cur_mfe = 0.0
        funding_collected = 0.0

        for i in range(len(df)):
            ts_iso = str(times[i])
            ts_date = str(times[i].date())

            # Consec loss halt: if halted, force-close open position at market and skip new entries
            if sym in halt_until and ts_iso < halt_until[sym]:
                if in_trade:
                    net_pnl_usd, is_loss = _close_position(
                        pos=pos, exit_price=closes[i], exit_reason="halt_force_close",
                        cur_mae=cur_mae, cur_mfe=cur_mfe, hold_bars=i - entry_idx,
                        funding_collected=funding_collected, cost_usd_per_trade=cost_usd_per_trade,
                        ts_iso=ts_iso, ts_date=ts_date,
                    )
                    cum_pnl += net_pnl_usd
                    daily_pnl[ts_date] = daily_pnl.get(ts_date, 0) + net_pnl_usd
                    print(f"  [{sym} {policy['bucket']}] CLOSED halt_force_close: entry={pos.entry_price:.2f} exit={closes[i]:.2f}  net=${net_pnl_usd:+.2f} (cum=${cum_pnl:+.2f})  hold={i-entry_idx}h")
                    in_trade = False
                    pos = None
                continue

            # Daily loss breaker: if -3% for the day, force-close open position at market
            if daily_pnl.get(ts_date, 0) <= -BANKROLL * DAILY_LOSS_LIMIT_PCT:
                if in_trade:
                    net_pnl_usd, is_loss = _close_position(
                        pos=pos, exit_price=closes[i], exit_reason="daily_loss_breaker",
                        cur_mae=cur_mae, cur_mfe=cur_mfe, hold_bars=i - entry_idx,
                        funding_collected=funding_collected, cost_usd_per_trade=cost_usd_per_trade,
                        ts_iso=ts_iso, ts_date=ts_date,
                    )
                    cum_pnl += net_pnl_usd
                    daily_pnl[ts_date] = daily_pnl.get(ts_date, 0) + net_pnl_usd
                    print(f"  [{sym} {policy['bucket']}] CLOSED daily_loss_breaker: entry={pos.entry_price:.2f} exit={closes[i]:.2f}  net=${net_pnl_usd:+.2f} (cum=${cum_pnl:+.2f})  hold={i-entry_idx}h")
                    in_trade = False
                    pos = None
                continue

            if not in_trade:
                if sig.iloc[i] == 1 and i + 1 < len(df):
                    in_trade = True
                    entry_price = closes[i]
                    entry_idx = i
                    cur_mae = 0.0
                    cur_mfe = 0.0
                    funding_collected = 0.0
                    decision_id = gen_id()
                    paper_id = paper_trade_id(sym, times[i])
                    pos = PaperPosition(
                        symbol=sym,
                        bucket=policy["bucket"],
                        side="long",
                        entry_ts=ts_iso,
                        entry_price=float(entry_price),
                        entry_funding=float(funds[i]),
                        notional_usd=float(notional_usd),
                        stop_pct=float(stop_pct),
                        tp_pct=float(tp_pct),
                        max_hold_h=int(max_hold),
                        risk_usd=float(risk_usd),
                        decision_id=decision_id,
                        paper_id=paper_id,
                        status="open",
                    )
            else:
                # Update MAE/MFE
                bar_mae = (lows[i] - pos.entry_price) / pos.entry_price
                bar_mfe = (highs[i] - pos.entry_price) / pos.entry_price
                cur_mae = min(cur_mae, bar_mae)
                cur_mfe = max(cur_mfe, bar_mfe)
                # Accrue funding for this bar (long, if fund<0, receive)
                if funds[i] < 0:
                    funding_collected += abs(funds[i]) * pos.notional_usd

                hold_bars = i - entry_idx
                tp_price = pos.entry_price * (1 + tp_pct)
                sl_price = pos.entry_price * (1 - stop_pct)

                exit_now = False
                exit_reason = ""
                exit_price = closes[i]

                if lows[i] <= sl_price:
                    exit_now = True
                    exit_reason = "stop_loss"
                    exit_price = sl_price
                elif highs[i] >= tp_price:
                    exit_now = True
                    exit_reason = "take_profit"
                    exit_price = tp_price
                elif hold_bars >= max_hold:
                    exit_now = True
                    exit_reason = "max_hold"

                if exit_now:
                    net_pnl_usd, is_loss = _close_position(
                        pos=pos, exit_price=exit_price, exit_reason=exit_reason,
                        cur_mae=cur_mae, cur_mfe=cur_mfe, hold_bars=hold_bars,
                        funding_collected=funding_collected, cost_usd_per_trade=cost_usd_per_trade,
                        ts_iso=ts_iso, ts_date=ts_date,
                    )
                    cum_pnl += net_pnl_usd
                    daily_pnl[ts_date] = daily_pnl.get(ts_date, 0) + net_pnl_usd

                    # Consec loss tracking
                    if is_loss:
                        consec_loss += 1
                        if consec_loss >= CONSEC_LOSS_HALT:
                            halt_until[sym] = (times[i] + pd.Timedelta(hours=24)).isoformat()
                            print(f"  [{sym}] consec loss halt: {consec_loss} losses, halt until {halt_until[sym]}")
                            consec_loss = 0
                    else:
                        consec_loss = 0

                    print(f"  [{sym} {policy['bucket']}] CLOSED {exit_reason}: entry={pos.entry_price:.2f} exit={exit_price:.2f}  net=${net_pnl_usd:+.2f} (cum=${cum_pnl:+.2f})  hold={hold_bars}h  fund=${funding_collected:+.4f}")
                    in_trade = False
                    pos = None

    print(f"\nTotal closed: {sum(1 for p in load_existing_positions() if p.get('status') == 'closed')}  cum PnL: ${cum_pnl:+.2f}")


# -----------------------------------------------------------------------------
# Mode: live — process new bars since last run (cron-friendly)
# -----------------------------------------------------------------------------

def _process_bars(
    sym: str,
    policy: dict,
    df: pd.DataFrame,
    start_idx: int,
    open_pos: PaperPosition | None,
    consec_loss: int,
    halt_until: dict,
    cum_pnl: float,
    daily_pnl: dict,
) -> tuple[PaperPosition | None, int, float, float, float]:
    """Process bars from start_idx. Returns (open_pos, consec_loss, cum_pnl, total_funding, total_price)."""
    closes = df["close"].values
    highs = df["high"].values
    lows = df["low"].values
    funds = df["funding_actual"].values
    times = df.index

    stop_pct = policy["stop_pct"]
    tp_pct = policy["tp_pct"]
    max_hold = policy["max_hold_h"]
    risk_usd = RISK_PER_TRADE_USD
    notional_usd = min(risk_usd / stop_pct, BANKROLL * 10)
    cost_usd_per_trade = (COST_BPS_ROUND_TRIP / 10_000.0) * notional_usd

    pos = open_pos
    in_trade = pos is not None
    if in_trade:
        # Reconstruct in-trade state from the existing pos
        entry_price = pos.entry_price
        # Default: assume position was opened before start_idx (most common case)
        # Use 0 so hold_bars >= max_hold fires immediately for stale positions
        entry_idx = 0
        # Try to find the actual entry index in the panel via searchsorted
        try:
            entry_dt = pd.Timestamp(pos.entry_ts)
            # If tz-naive, localize to UTC; if tz-aware, convert
            if entry_dt.tzinfo is None:
                if times.tz is not None:
                    entry_dt = entry_dt.tz_localize(times.tz)
            else:
                if times.tz is not None:
                    entry_dt = entry_dt.tz_convert(times.tz)
            # Search in the FULL bar series, not the new_bars slice
            entry_idx = times.searchsorted(entry_dt)[0] if hasattr(times, "searchsorted") else 0
            entry_idx = max(0, entry_idx)
        except Exception:
            entry_idx = 0
        cur_mae = pos.mae_pct / 100.0
        cur_mfe = pos.mfe_pct / 100.0
        funding_collected = pos.funding_collected_usd
    else:
        entry_price = 0.0
        entry_idx = 0
        cur_mae = 0.0
        cur_mfe = 0.0
        funding_collected = 0.0

    sig = signal_funding_neg_fade(df, funding_col="funding_actual", neg_threshold=NEG_THRESHOLD)

    for i in range(start_idx, len(df)):
        ts_iso = str(times[i])
        ts_date = str(times[i].date())

        # Consec loss halt
        if sym in halt_until and ts_iso < halt_until[sym]:
            if in_trade:
                net_pnl_usd, _ = _close_position(
                    pos=pos, exit_price=closes[i], exit_reason="halt_force_close",
                    cur_mae=cur_mae, cur_mfe=cur_mfe, hold_bars=i - entry_idx,
                    funding_collected=funding_collected, cost_usd_per_trade=cost_usd_per_trade,
                    ts_iso=ts_iso, ts_date=ts_date,
                )
                cum_pnl += net_pnl_usd
                daily_pnl[ts_date] = daily_pnl.get(ts_date, 0) + net_pnl_usd
                print(f"  [{sym} {policy['bucket']}] CLOSED halt_force_close: net=${net_pnl_usd:+.2f} (cum=${cum_pnl:+.2f})")
                in_trade = False
                pos = None
            continue

        # Daily loss breaker
        if daily_pnl.get(ts_date, 0) <= -BANKROLL * DAILY_LOSS_LIMIT_PCT:
            if in_trade:
                net_pnl_usd, _ = _close_position(
                    pos=pos, exit_price=closes[i], exit_reason="daily_loss_breaker",
                    cur_mae=cur_mae, cur_mfe=cur_mfe, hold_bars=i - entry_idx,
                    funding_collected=funding_collected, cost_usd_per_trade=cost_usd_per_trade,
                    ts_iso=ts_iso, ts_date=ts_date,
                )
                cum_pnl += net_pnl_usd
                daily_pnl[ts_date] = daily_pnl.get(ts_date, 0) + net_pnl_usd
                print(f"  [{sym} {policy['bucket']}] CLOSED daily_loss_breaker: net=${net_pnl_usd:+.2f} (cum=${cum_pnl:+.2f})")
                in_trade = False
                pos = None
            continue

        if not in_trade:
            if sig.iloc[i] == 1 and i + 1 < len(df):
                decision_id = gen_id()
                paper_id = paper_trade_id(sym, times[i])
                if paper_id_exists(paper_id):
                    pass  # already in JSONL, skip
                else:
                    in_trade = True
                    entry_price = closes[i]
                    entry_idx = i
                    cur_mae = 0.0
                    cur_mfe = 0.0
                    funding_collected = 0.0
                    pos = PaperPosition(
                        symbol=sym,
                        bucket=policy["bucket"],
                        side="long",
                        entry_ts=ts_iso,
                        entry_price=float(entry_price),
                        entry_funding=float(funds[i]),
                        notional_usd=float(notional_usd),
                        stop_pct=float(stop_pct),
                        tp_pct=float(tp_pct),
                        max_hold_h=int(max_hold),
                        risk_usd=float(risk_usd),
                        decision_id=decision_id,
                        paper_id=paper_id,
                        status="open",
                    )
        else:
            bar_mae = (lows[i] - entry_price) / entry_price
            bar_mfe = (highs[i] - entry_price) / entry_price
            cur_mae = min(cur_mae, bar_mae)
            cur_mfe = max(cur_mfe, bar_mfe)
            if funds[i] < 0:
                funding_collected += abs(funds[i]) * pos.notional_usd

            hold_bars = i - entry_idx
            tp_price = entry_price * (1 + tp_pct)
            sl_price = entry_price * (1 - stop_pct)

            exit_now = False
            exit_reason = ""
            exit_price = closes[i]

            if lows[i] <= sl_price:
                exit_now = True
                exit_reason = "stop_loss"
                exit_price = sl_price
            elif highs[i] >= tp_price:
                exit_now = True
                exit_reason = "take_profit"
                exit_price = tp_price
            elif hold_bars >= max_hold:
                exit_now = True
                exit_reason = "max_hold"

            if exit_now:
                net_pnl_usd, is_loss = _close_position(
                    pos=pos, exit_price=exit_price, exit_reason=exit_reason,
                    cur_mae=cur_mae, cur_mfe=cur_mfe, hold_bars=hold_bars,
                    funding_collected=funding_collected, cost_usd_per_trade=cost_usd_per_trade,
                    ts_iso=ts_iso, ts_date=ts_date,
                )
                cum_pnl += net_pnl_usd
                daily_pnl[ts_date] = daily_pnl.get(ts_date, 0) + net_pnl_usd
                if is_loss:
                    consec_loss += 1
                    if consec_loss >= CONSEC_LOSS_HALT:
                        halt_until[sym] = (times[i] + pd.Timedelta(hours=24)).isoformat()
                        print(f"  [{sym}] consec loss halt: {consec_loss} losses, halt until {halt_until[sym]}")
                        consec_loss = 0
                else:
                    consec_loss = 0
                print(f"  [{sym} {policy['bucket']}] CLOSED {exit_reason}: entry={pos.entry_price:.2f} exit={exit_price:.2f}  net=${net_pnl_usd:+.2f} (cum=${cum_pnl:+.2f})  hold={hold_bars}h  fund=${funding_collected:+.4f}")
                in_trade = False
                pos = None

    # If still in trade at end, save it as an open position
    if in_trade and pos is not None:
        # update MAE/MFE/funding on the live pos object
        pos.mae_pct = float(cur_mae * 100)
        pos.mfe_pct = float(cur_mfe * 100)
        pos.funding_collected_usd = float(funding_collected)
        pos.hold_bars = int(len(df) - 1 - entry_idx)
        # Don't write to JSONL yet — keep in state file
    elif in_trade is False and pos is None:
        pos = None  # explicit

    return pos, consec_loss, cum_pnl, halt_until.get(sym, ""), daily_pnl.get(str(times[-1].date()), 0.0)


def mode_live(symbol_filter: list[str] | None = None) -> None:
    """Process new bars since last run. Cron-friendly: idempotent, appends only new positions."""
    syms = symbol_filter or ALL_SYMBOLS
    state = load_state()
    last_processed = state.get("last_processed_ts", {})
    open_positions = state.get("open_positions", {})

    print(f"=== paper: LIVE mode (process new bars) ===")
    print(f"  bankroll: ${BANKROLL:.0f}  risk/trade: ${RISK_PER_TRADE_USD:.0f}")
    print(f"  state file: {STATE_PATH}")
    print(f"  last_processed_ts: {last_processed}")
    if open_positions:
        print(f"  open positions:")
        for s, p in open_positions.items():
            if p is None:
                print(f"    {s}: (none)")
            else:
                print(f"    {s}: entry={p.get('entry_price')} hold={p.get('hold_bars')}h status={p.get('status')}")
    print()

    new_state = {"last_processed_ts": dict(last_processed), "open_positions": {}}

    for sym in syms:
        try:
            df, label = load_hl_with_funding(sym)
        except Exception as e:
            print(f"  {sym}: load failed: {e}")
            continue
        if sym not in PER_ASSET_POLICY:
            # No calibrated stop/tp for this symbol yet. Skip rather than
            # crash the whole run — ALL_SYMBOLS includes research names
            # that have never been calibrated, and an uncalibrated symbol
            # must not be paper-traded at a guessed size.
            print(f"  {sym}: no PER_ASSET_POLICY entry, skipping")
            continue
        policy = PER_ASSET_POLICY[sym]

        last_ts_str = last_processed.get(sym)
        if last_ts_str:
            try:
                last_ts = pd.Timestamp(last_ts_str)
                if last_ts.tzinfo is not None:
                    last_ts = last_ts.tz_localize(None)
                # Find index of first bar AFTER last_ts
                if df.index.tzinfo is not None:
                    start_idx = df.index.tz_localize(None).get_indexer([last_ts], method="bfill")[0] + 1
                else:
                    start_idx = df.index.get_indexer([last_ts], method="bfill")[0] + 1
                if start_idx < 0 or start_idx >= len(df):
                    start_idx = max(0, start_idx)
            except Exception as e:
                print(f"  {sym}: state parse failed ({e}), starting from 0")
                start_idx = 0
        else:
            start_idx = 0

        if start_idx >= len(df):
            print(f"  {sym}: no new bars (last_ts={last_ts_str})")
            new_state["last_processed_ts"][sym] = str(df.index[-1])
            new_state["open_positions"][sym] = open_positions.get(sym)  # preserve
            continue

        print(f"  {sym}: processing {len(df) - start_idx} new bars (from {df.index[start_idx]})")

        # Reconstruct open position
        open_pos = None
        if sym in open_positions and open_positions[sym] is not None and open_positions[sym].get("status") == "open":
            try:
                p = open_positions[sym]
                open_pos = PaperPosition(**p)
            except Exception as e:
                print(f"  {sym}: failed to restore open position: {e}")
                open_pos = None

        # Per-symbol state for this run
        consec_loss = 0
        halt_until: dict = {}
        cum_pnl = 0.0  # local to this run
        daily_pnl: dict = {}

        pos, consec_loss, cum_pnl, halt_ts, _ = _process_bars(
            sym=sym, policy=policy, df=df, start_idx=start_idx,
            open_pos=open_pos, consec_loss=consec_loss, halt_until=halt_until,
            cum_pnl=cum_pnl, daily_pnl=daily_pnl,
        )

        # Update state
        new_state["last_processed_ts"][sym] = str(df.index[-1])
        if pos is not None:
            new_state["open_positions"][sym] = asdict(pos)
            print(f"  {sym}: position still open (entry={pos.entry_price}, hold={pos.hold_bars}h)")
        else:
            new_state["open_positions"][sym] = None
        if sym in halt_until:
            new_state.setdefault("halt_until", {})[sym] = halt_until[sym]

    save_state(new_state)
    print(f"\nstate updated -> {STATE_PATH}")
    print(f"  last_processed_ts: {new_state['last_processed_ts']}")
    open_count = sum(1 for v in new_state["open_positions"].values() if v is not None)
    print(f"  open positions: {open_count}")


# -----------------------------------------------------------------------------
# Mode: live trading (real mainnet orders, HYPE-only, OFF by default)
# -----------------------------------------------------------------------------

def _live_trading_guard_ok() -> tuple[bool, str]:
    """Three guard checks before any real order can be placed."""
    if not LIVE_TRADING_ENABLED:
        return False, "LIVE_TRADING_ENABLED is False; flip the flag in scripts/paper_funding_neg_fade.py"
    if not TESTNET_PROOF_PATH.exists():
        return False, f"missing testnet proof at {TESTNET_PROOF_PATH}"
    try:
        proof = json.loads(TESTNET_PROOF_PATH.read_text(encoding="utf-8"))
    except Exception as e:
        return False, f"failed to parse testnet proof: {e}"
    if proof.get("status") != "bracket_proof_passed":
        return False, f"testnet proof status is {proof.get('status')!r}, expected 'bracket_proof_passed'"
    if proof.get("protective_stop_visible") is not True:
        return False, "testnet proof did not show protective_stop_visible=True"
    return True, "ok"


# -----------------------------------------------------------------------------
# Safety infrastructure (added 2026-08-22)
# -----------------------------------------------------------------------------
# Runtime kill switch:
#   touch data/live_kill_switch.flag  -> halt live trading immediately
#   rm data/live_kill_switch.flag     -> resume (still subject to all other guards)
# Consec-loss / drawdown state persists across ticks in data/live_funding_neg_fade_state.json
# so the 3-loss halt and 40% drawdown kill survive process restarts.
# Heartbeat: data/live_heartbeat.txt is rewritten every run; stale = cron died.
# Circuit log: data/live_circuit_log.jsonl is append-only for post-mortem.

def _kill_switch_active() -> bool:
    return KILL_SWITCH_PATH.exists()


def _load_live_state(path=None, bankroll: float | None = None) -> dict:
    """Load persisted trading state. Returns safe defaults if missing.

    path/bankroll default to the mainnet file and bankroll; testnet passes its
    own so a testnet run can never inherit or clobber mainnet circuit state.
    """
    path = path or LIVE_STATE_PATH
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"  WARN: state parse failed ({e}); starting fresh")
    return {
        "consecutive_losses": 0,
        "last_loss_ts": None,
        "last_win_ts": None,
        "peak_equity_usd": LIVE_BANKROLL_USD if bankroll is None else bankroll,
        "halted_until": None,
        "stopped": False,
        "total_pnl_usd": 0.0,
        "trade_count": 0,
    }


def _save_live_state(state: dict, path=None) -> None:
    path = path or LIVE_STATE_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")


def _log_circuit_event(event: str, **fields) -> None:
    """Append a circuit event to the post-mortem log."""
    LIVE_CIRCUIT_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    rec = {"ts_utc": pd.Timestamp.utcnow().isoformat(), "event": event, **fields}
    with LIVE_CIRCUIT_LOG_PATH.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(rec) + "\n")


def _check_live_circuits(state: dict, current_equity_usd: float) -> tuple[bool, str]:
    """Decide whether new orders are allowed. Returns (allowed, reason)."""
    # Hard kill: file flag
    if _kill_switch_active():
        return False, f"runtime kill switch present at {KILL_SWITCH_PATH}; rm to resume"
    # Hard kill: state.stopped (set by drawdown)
    if state.get("stopped"):
        return False, "state.stopped=True (drawdown kill tripped); reset state to resume"
    # Consec-loss threshold: defense in depth — if counter is at the halt
    # threshold but halted_until is unset (e.g. state was loaded but not
    # updated, or file was hand-edited), still refuse. _record_trade_outcome
    # also sets halted_until, but the threshold alone is sufficient.
    consec = int(state.get("consecutive_losses") or 0)
    if consec >= LIVE_CONSEC_LOSS_HALT:
        return False, f"consec_losses={consec} >= {LIVE_CONSEC_LOSS_HALT}; reset data/live_funding_neg_fade_state.json to resume"
    # 24h halt from consec losses
    halted_until = state.get("halted_until")
    if halted_until:
        try:
            halt_ts = pd.Timestamp(halted_until)
            now = pd.Timestamp.utcnow()
            if now < halt_ts:
                return False, f"halted until {halt_ts.isoformat()} (consec-loss pause)"
        except Exception:
            pass
    # Drawdown kill (40% of starting bankroll)
    peak = max(float(state.get("peak_equity_usd") or LIVE_BANKROLL_USD), current_equity_usd)
    if current_equity_usd < LIVE_BANKROLL_USD * (1 - LIVE_DRAWDOWN_KILL_PCT):
        state["stopped"] = True
        _save_live_state(state)
        _log_circuit_event("drawdown_kill", equity=current_equity_usd, peak=peak)
        return False, f"drawdown kill: equity ${current_equity_usd:.2f} <= ${LIVE_BANKROLL_USD * (1 - LIVE_DRAWDOWN_KILL_PCT):.2f}"
    return True, "ok"


def _record_trade_outcome(state: dict, pnl_usd: float) -> None:
    """Update persisted state after a closed trade. Stops on 3 consec losses."""
    now_iso = pd.Timestamp.utcnow().isoformat()
    state["trade_count"] = int(state.get("trade_count") or 0) + 1
    state["total_pnl_usd"] = float(state.get("total_pnl_usd") or 0.0) + pnl_usd
    if pnl_usd < 0:
        state["consecutive_losses"] = int(state.get("consecutive_losses") or 0) + 1
        state["last_loss_ts"] = now_iso
        if state["consecutive_losses"] >= LIVE_CONSEC_LOSS_HALT:
            state["halted_until"] = (pd.Timestamp.utcnow() + pd.Timedelta(hours=24)).isoformat()
            _log_circuit_event(
                "consec_loss_halt",
                consecutive_losses=state["consecutive_losses"],
                halted_until=state["halted_until"],
                trade_pnl_usd=pnl_usd,
            )
    else:
        state["consecutive_losses"] = 0
        state["last_win_ts"] = now_iso
    _save_live_state(state)


def _reconcile_on_chain(info, user: str, local_open_keys: set[str]) -> list[dict]:
    """Fetch exchange state and log any drift vs local view. Best-effort."""
    try:
        state = info.user_state(user)
    except Exception as e:
        return [{"event": "reconcile_failed", "error": str(e)}]
    on_chain_positions = []
    diffs = []
    positions = (state or {}).get("assetPositions") or []
    for ap in positions:
        pos = (ap or {}).get("position") or {}
        coin = pos.get("coin")
        szi = float(pos.get("szi", 0))
        if szi == 0 or coin is None:
            continue
        on_chain_positions.append({"coin": coin, "szi": szi, "entryPx": pos.get("entryPx")})
        # diff: every on-chain position should be in local view (best-effort)
        # Note: local_keys track our bracket oids, not (coin,side). For now we just
        # log a "we see a position" line for post-mortem.
    diffs.append({"event": "reconcile_ok", "on_chain_count": len(on_chain_positions), "local_count": len(local_open_keys)})
    if on_chain_positions:
        diffs.append({"event": "on_chain_positions", "positions": on_chain_positions})
    return diffs


def _write_heartbeat(status: str, extra: str = "") -> None:
    HEARTBEAT_PATH.parent.mkdir(parents=True, exist_ok=True)
    ts = pd.Timestamp.utcnow().isoformat()
    HEARTBEAT_PATH.write_text(f"{ts}\t{status}\t{extra}\n", encoding="utf-8")


def _load_live_open_positions(path=None) -> list[dict]:
    """Currently open positions, persisted between ticks.

    path defaults to the mainnet file; the testnet mode passes its own so the
    two venues can never read or overwrite each other's position state.
    """
    path = path or LIVE_OPEN_POSITIONS_PATH
    if not path.exists():
        return []
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []


def _save_live_open_positions(positions: list[dict], path=None) -> None:
    path = path or LIVE_OPEN_POSITIONS_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(positions, indent=2, sort_keys=True), encoding="utf-8"
    )


def _funding_during_hold(sym: str, entry_ts_iso: str, exit_ts_iso: str, notional_usd: float = 1000.0) -> float:
    """Estimate funding collected between entry and exit.

    Reads asset_ctx JSONL files for the symbol, sums (funding_actual * notional)
    over the bars whose timestamp falls in [entry_ts, exit_ts]. For longs, a
    negative funding rate means longs receive. Same convention as the paper mode.

    Args:
        sym: Trading symbol (e.g., "HYPE", "BTC")
        entry_ts_iso: ISO timestamp of position entry
        exit_ts_iso: ISO timestamp of position exit
        notional_usd: Position notional in USD (required for accurate P&L)

    Returns: Funding collected in USD, or 0.0 if data is missing.
    """
    if notional_usd <= 0:
        return 0.0
    try:
        # Force UTC-aware to match the +00:00 timestamps in asset_ctx files
        entry_dt = pd.Timestamp(entry_ts_iso)
        if entry_dt.tz is None:
            entry_dt = entry_dt.tz_localize("UTC")
        exit_dt = pd.Timestamp(exit_ts_iso)
        if exit_dt.tz is None:
            exit_dt = exit_dt.tz_localize("UTC")
    except Exception:
        return 0.0
    # Asset ctx files are {symbol}_{date}.jsonl; for HIP-3 the filename uses
    # an underscore in place of the colon (xyz_gold_2026-08-22.jsonl).
    fn_sym = sym.lower().replace(":", "_")
    asset_dir = PROJECT_ROOT / "data" / "asset_ctx"
    if not asset_dir.exists():
        return 0.0
    # Find all matching files
    matches = sorted(asset_dir.glob(f"{fn_sym}_*.jsonl"))
    total_collected = 0.0
    for f in matches:
        try:
            with f.open(encoding="utf-8") as fh:
                for line in fh:
                    try:
                        rec = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    poll_ts = _parse_iso(rec.get("poll_ts"))
                    if poll_ts is None:
                        continue
                    # Normalize to UTC-aware
                    if poll_ts.tz is None:
                        poll_ts = poll_ts.tz_localize("UTC")
                    if poll_ts < entry_dt or poll_ts > exit_dt:
                        continue
                    ctx = rec.get("context") or {}
                    fund = float(ctx.get("funding") or 0.0)
                    if fund < 0:
                        # Funding rate is per-hour. Multiply rate * notional to get USD.
                        total_collected += abs(fund) * notional_usd
        except OSError:
            continue
    return total_collected


def _detect_and_record_live_closes(info, user: str, state: dict) -> int:
    """Reconcile local open positions vs on-chain user_state. Append closes
    to LIVE_POSITIONS_PATH and update state (total_pnl_usd, consec_losses,
    peak_equity). Returns the number of closes recorded."""
    open_local = _load_live_open_positions()
    if not open_local:
        return 0

    try:
        on_chain = info.user_state(user) or {}
    except Exception as e:
        _log_circuit_event("live_close_detect_failed", error=str(e))
        return 0
    asset_positions = on_chain.get("assetPositions") or []
    on_chain_keys: set[tuple[str, str]] = set()
    on_chain_marks: dict[str, float] = {}
    for ap in asset_positions:
        pos = (ap or {}).get("position") or {}
        coin = pos.get("coin")
        szi = float(pos.get("szi", 0))
        if szi == 0 or coin is None:
            continue
        # We only track longs (LIVE_SYMBOLS is long-only); treat any non-zero
        # szi as "open" for our local key.
        on_chain_keys.add((coin, "long"))
        # markPx is not directly in user_state; leave empty for now, the
        # caller can fetch via meta if needed.

    LIVE_POSITIONS_PATH.parent.mkdir(parents=True, exist_ok=True)
    still_open: list[dict] = []
    closes_recorded = 0
    pnl_delta = 0.0
    is_loss_streak = []
    for pos in open_local:
        sym = pos.get("symbol")
        if (sym, "long") in on_chain_keys:
            still_open.append(pos)
            continue
        # Position closed between ticks
        entry_px = float(pos.get("entry_px", 0))
        notional = float(pos.get("notional_usd", 0))
        size_coin = float(pos.get("size_coin", 0))
        # Fetch exit price from live mark. If unavailable, log warning and
        # mark exit_reason to indicate P&L may be incomplete.
        exit_px = None
        exit_price_available = False
        try:
            ctx_resp = info.meta_and_asset_ctxs() or {}
            for tup in ctx_resp or []:
                if not isinstance(tup, (list, tuple)) or len(tup) < 2:
                    continue
                universe = tup[0] or []
                ctxs = tup[1] or []
                for u, c in zip(universe, ctxs):
                    if u.get("name") == sym:
                        m = float((c or {}).get("markPx") or 0)
                        if m > 0:
                            exit_px = m
                            exit_price_available = True
                        break
        except Exception as e:
            print(f"  WARN: failed to fetch exit price for {sym}: {e}")
        if not exit_price_available:
            print(f"  WARN: no exit price for {sym}, P&L will be funding-only")
            exit_px = entry_px  # Fallback but log indicates incomplete

        # Compute P&L
        price_pnl_usd = (exit_px - entry_px) / entry_px * notional if entry_px > 0 else 0.0
        # Funding estimate: sum the funding in USD [entry_ts, now]
        entry_ts = pos.get("entry_ts") or pos.get("signal_ts") or ""
        now_iso = pd.Timestamp.utcnow().isoformat()
        funding_collected_usd = _funding_during_hold(sym, entry_ts, now_iso, notional)
        cost_usd = notional * 0.0008  # 8 bps round trip
        net_pnl_usd = price_pnl_usd - cost_usd + funding_collected_usd
        is_loss = net_pnl_usd < 0

        closed_record = {
            "paper_id": pos.get("paper_id"),
            "symbol": sym,
            "bucket": "v1",
            "side": "long",
            "entry_ts": entry_ts,
            "entry_price": entry_px,
            "entry_funding": pos.get("entry_funding", 0.0),
            "notional_usd": notional,
            "stop_pct": pos.get("stop_pct", 0.0),
            "tp_pct": pos.get("tp_pct", 0.0),
            "max_hold_h": pos.get("max_hold_h", 0),
            "risk_usd": pos.get("risk_usd", 0.0),
            "decision_id": pos.get("decision_id", ""),
            "status": "closed",
            "exit_ts": now_iso,
            "exit_price": exit_px,
            "exit_reason": "close_detected_via_user_state" + ("_no_exit_price" if not exit_price_available else ""),
            "mae_pct": 0.0,
            "mfe_pct": 0.0,
            "hold_bars": 0,
            "funding_collected_usd": float(funding_collected_usd),
            "price_pnl_usd": float(price_pnl_usd),
            "cost_usd": float(cost_usd),
            "net_pnl_usd": float(net_pnl_usd),
            "cum_pnl_usd": 0.0,  # recomputed below
            "notes": "auto-recorded by mode_live_trading close-detector",
        }
        # Idempotency: skip if this paper_id already in LIVE_POSITIONS_PATH
        existing_ids: set[str] = set()
        if LIVE_POSITIONS_PATH.exists():
            try:
                with LIVE_POSITIONS_PATH.open(encoding="utf-8") as fh:
                    for ln in fh:
                        try:
                            existing_ids.add(json.loads(ln).get("paper_id", ""))
                        except json.JSONDecodeError:
                            continue
            except OSError:
                pass
        if closed_record["paper_id"] in existing_ids:
            still_open.append(pos)  # keep tracking; will be removed by a re-detect
            continue
        with LIVE_POSITIONS_PATH.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(closed_record) + "\n")
        closes_recorded += 1
        pnl_delta += net_pnl_usd
        is_loss_streak.append(is_loss)
        _log_circuit_event(
            "live_close_recorded",
            symbol=sym,
            paper_id=closed_record["paper_id"],
            net_pnl_usd=net_pnl_usd,
            price_pnl_usd=price_pnl_usd,
            funding_collected_usd=funding_collected_usd,
        )

    # Persist updated open positions
    _save_live_open_positions(still_open)

    # Update state totals
    if closes_recorded:
        prev_total = float(state.get("total_pnl_usd") or 0.0)
        prev_count = int(state.get("trade_count") or 0)
        prev_consec = int(state.get("consecutive_losses") or 0)
        new_total = prev_total + pnl_delta
        new_count = prev_count + closes_recorded
        # Consec losses: if last close was a loss, increment from 0; if win, reset to 0
        last_was_loss = is_loss_streak[-1] if is_loss_streak else False
        new_consec = prev_consec + 1 if last_was_loss else 0
        peak = float(state.get("peak_equity_usd") or LIVE_BANKROLL_USD)
        new_equity = LIVE_BANKROLL_USD + new_total
        new_peak = max(peak, new_equity)
        state["total_pnl_usd"] = new_total
        state["trade_count"] = new_count
        state["consecutive_losses"] = new_consec
        state["peak_equity_usd"] = new_peak
        state["last_close_ts"] = pd.Timestamp.utcnow().isoformat()
        # Halt on 3 consec losses
        if new_consec >= LIVE_CONSEC_LOSS_HALT:
            halt_until = pd.Timestamp.utcnow() + pd.Timedelta(hours=24)
            state["halted_until"] = halt_until.isoformat()
            _log_circuit_event("live_halt_triggered", reason=f"consec_losses={new_consec}", halted_until=state["halted_until"])
        _save_live_state(state)
    return closes_recorded


def _parse_iso(s: str | None):
    """Local ISO parser to avoid pulling in extra deps."""
    if not s:
        return None
    try:
        if s.endswith("Z"):
            s = s[:-1] + "+00:00"
        return pd.Timestamp(s)
    except Exception:
        return None


def _cross_venue_snapshot(sym: str, hl_funding_at_signal: float | None) -> dict:
    """Best-effort snapshot of Binance funding for a symbol at signal time.

    Returns a dict with binance_sym, binance_funding_per_hour, delta, age_seconds.
    Used to annotate live order records so we can later measure whether
    cross-venue divergence correlates with trade outcomes. If no recent
    Binance data is available (record older than 30 min or file missing),
    returns just {available: False, reason: ...}.
    """
    try:
        from scripts.binance_delta import compute_delta
        info = compute_delta(sym, hl_funding_at_signal)
        return {
            "available": info.get("binance_funding_per_hour") is not None,
            "binance_sym": info.get("binance_sym"),
            "binance_funding_per_hour": info.get("binance_funding_per_hour"),
            "delta_per_hour": info.get("delta"),
            "boost_eligible": info.get("boost_eligible", False),
            "fetched_ts": info.get("fetched_ts"),
            "age_seconds": info.get("age_seconds"),
        }
    except Exception as e:
        return {"available": False, "reason": f"compute_delta failed: {e}"}



def _testnet_guard_ok() -> tuple[bool, str]:
    """Testnet execution is only allowed to reach testnet.

    Deliberately does NOT consult LIVE_TRADING_ENABLED -- no mainnet funds are
    involved, so gating this behind the mainnet flag would push people to flip
    that flag for testing, which is the opposite of safe. It requires instead
    that .env is actually pointed at testnet, so a box configured for mainnet
    cannot run this mode at all.
    """
    env = os.getenv("HYPERLIQUID_ENV", "").strip().lower()
    if env != "testnet":
        return False, (f"HYPERLIQUID_ENV is {env or 'unset'!r}, refusing: this mode "
                       f"only runs against testnet")
    if _kill_switch_active():
        return False, "kill switch is active"
    return True, "testnet guard passed"


def mode_live_trading() -> None:
    """Walk LIVE_SYMBOLS bars, build bracket intents, submit via OrderManager.

    Safety chain (all must pass):
      1. LIVE_TRADING_ENABLED (one-line flip in this file)
      2. testnet proof on disk with status=bracket_proof_passed
      3. runtime kill switch absent (data/live_kill_switch.flag)
      4. persisted state not stopped / not in halt window
      5. equity above 40% drawdown kill
      6. on-chain reconcile (logs drift; not a hard refuse)

    Off by default (LIVE_TRADING_ENABLED = False). Every order attempt is
    logged to LIVE_ORDERS_PATH. State persists in LIVE_STATE_PATH.
    """
    print("=== LIVE funding_neg_fade: real-order mode ===")
    print(f"  LIVE_TRADING_ENABLED = {LIVE_TRADING_ENABLED}")
    print(f"  LIVE_SYMBOLS         = {LIVE_SYMBOLS}")
    print(f"  LIVE_BANKROLL_USD    = ${LIVE_BANKROLL_USD:.0f}")
    print(f"  LIVE_RISK_USD        = ${LIVE_RISK_USD:.2f} per trade")
    print(f"  kill_switch          = {'ACTIVE' if _kill_switch_active() else 'clear'}")
    print()

    # Guard 1+2: code flag + testnet proof
    ok, reason = _live_trading_guard_ok()
    if not ok:
        print(f"  REFUSED: {reason}")
        _write_heartbeat("refused_guard", reason)
        return
    print(f"  guard 1+2 (code+testnet): {reason}")

    # Load persisted state
    state = _load_live_state()
    print(f"  state: consec_losses={state.get('consecutive_losses')} trade_count={state.get('trade_count')} total_pnl=${state.get('total_pnl_usd', 0):+.2f}")

    # Guard 3+4+5: kill switch, halt, drawdown
    current_equity = LIVE_BANKROLL_USD + float(state.get("total_pnl_usd") or 0.0)
    allowed, circuit_reason = _check_live_circuits(state, current_equity)
    if not allowed:
        print(f"  REFUSED: {circuit_reason}")
        _write_heartbeat("refused_circuit", circuit_reason)
        return
    print(f"  guard 3+4+5 (kill+halt+dd): {circuit_reason}")
    print()

    # Lazy import: OrderManager pulls in eth_account, hyperliquid SDK, etc.
    try:
        from src.execution.order_manager import (
            BracketOrderIntent, OrderManager, OrderResult,
        )
    except Exception as e:
        print(f"  REFUSED: could not import OrderManager: {e}")
        _write_heartbeat("refused_import", str(e))
        return

    # Build SDK clients from .env
    try:
        from dotenv import load_dotenv
        load_dotenv(PROJECT_ROOT / ".env")
        from eth_account import Account
        from hyperliquid.exchange import Exchange
        from hyperliquid.info import Info
        from hyperliquid.utils import constants
        pk = os.getenv("HYPERLIQUID_PRIVATE_KEY", "").strip()
        user = os.getenv("HYPERLIQUID_WALLET_ADDRESS", "").strip()
        if not pk.startswith("0x"):
            pk = "0x" + pk
        wallet = Account.from_key(pk)
        env_url = constants.MAINNET_API_URL  # live = mainnet
        info = Info(env_url, skip_ws=True)
        exchange = Exchange(wallet, env_url)
    except Exception as e:
        print(f"  REFUSED: could not build SDK clients: {e}")
        _write_heartbeat("refused_sdk", str(e))
        return

    # Guard 6: on-chain reconciliation
    print(f"  on-chain reconcile:")
    for d in _reconcile_on_chain(info, user, set()):
        print(f"    {d.get('event')}: {d}")
        _log_circuit_event(d.get("event", "reconcile"), **{k: v for k, v in d.items() if k != "event"})

    # Close-detect: append any positions that closed since the last tick to
    # LIVE_POSITIONS_PATH and update state totals. Runs BEFORE new orders so
    # the dashboard sees closed P&L even on the tick that opens a new trade.
    closes = _detect_and_record_live_closes(info, user, state)
    if closes:
        print(f"  close-detect: recorded {closes} closed live position(s)")
        # Re-load state to pick up the updated totals
        state = _load_live_state()

    om = OrderManager(
        exchange=exchange,
        info=info,
        bankroll=LIVE_BANKROLL_USD,
        risk_per_trade_pct=LIVE_RISK_USD / LIVE_BANKROLL_USD,
        env="mainnet",
    )

    LIVE_ORDERS_PATH.parent.mkdir(parents=True, exist_ok=True)
    print(f"  order log: {LIVE_ORDERS_PATH}")
    print()

    for sym in LIVE_SYMBOLS:
        try:
            df, _ = load_hl_with_funding(sym)
        except Exception as e:
            print(f"  {sym}: load failed: {e}")
            continue
        if sym not in PER_ASSET_POLICY:
            # No calibrated stop/tp for this symbol yet. Skip rather than
            # crash the whole run — ALL_SYMBOLS includes research names
            # that have never been calibrated, and an uncalibrated symbol
            # must not be paper-traded at a guessed size.
            print(f"  {sym}: no PER_ASSET_POLICY entry, skipping")
            continue
        policy = PER_ASSET_POLICY[sym]
        sig = signal_funding_neg_fade(df, funding_col="funding_actual", neg_threshold=NEG_THRESHOLD)
        # Walk bars; collect bracket intents for the most recent unfired signal.
        # sig carries df's DatetimeIndex, so sig[i] would be a label lookup and
        # raise KeyError on an integer -- take the values positionally.
        sig_v = sig.to_numpy() if hasattr(sig, "to_numpy") else sig
        closes = df["close"].values
        times = df.index
        last_signal_idx = -1
        for i in range(1, len(df)):
            if sig_v[i] and not sig_v[i - 1] and closes[i] > 0:
                last_signal_idx = i
        if last_signal_idx < 0:
            print(f"  {sym}: no fresh signal in this run")
            continue

        i = last_signal_idx
        entry_px = float(closes[i])
        sl_px = entry_px * (1 - policy["stop_pct"])
        tp_px = entry_px * (1 + policy["tp_pct"])
        notional = LIVE_RISK_USD / max(policy["stop_pct"], 1e-6)
        intent = BracketOrderIntent(
            signal_ts=times[i],
            symbol=sym,
            side="long",
            entry_px=entry_px,
            sl_px=sl_px,
            tp_px=tp_px,
            notional_usd=notional,
            reason=f"funding_neg_fade live {sym} signal {times[i]}",
        )
        print(f"  {sym}: signal @ {times[i]} entry={entry_px} sl={sl_px} tp={tp_px} notional=${notional:.0f}")
        try:
            result: OrderResult = om.execute_bracket_intent(intent)
        except Exception as e:
            print(f"  {sym}: OrderManager crashed: {e}")
            result = None
        record = {
            "ts_utc": pd.Timestamp.utcnow().isoformat(),
            "symbol": sym,
            "intent": {
                "signal_ts": str(times[i]),
                "side": "long",
                "entry_px": entry_px,
                "sl_px": sl_px,
                "tp_px": tp_px,
                "notional_usd": notional,
            },
            "cross_venue": _cross_venue_snapshot(sym, float(df["funding_actual"].iloc[i]) if "funding_actual" in df.columns else None),
            "result": (None if result is None else {
                "filled": result.filled,
                "status": result.status,
                "entry_oid": result.entry_oid,
                "tp_oid": result.tp_oid,
                "sl_oid": result.sl_oid,
                "size_coin": result.size_coin,
                "risk_verdict": str(result.risk_verdict),
                "error": result.error,
            }),
        }
        with LIVE_ORDERS_PATH.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(record) + "\n")
        if result is None or not result.filled:
            print(f"  {sym}: not filled (status={None if result is None else result.status}, error={None if result is None else result.error})")
        else:
            print(f"  {sym}: FILLED entry_oid={result.entry_oid} size={result.size_coin}")
            # Persist this open position so the next tick's close-detector
            # can find it. Without this, the position would be invisible to
            # the dashboard's live_pnl_summary until a manual write.
            decision_id = record["intent"].get("signal_ts", "")
            paper_id = f"live-fnf-{sym}-{pd.Timestamp.utcnow().strftime('%Y%m%d%H%M%S')}-{result.entry_oid or 'x'}"
            open_pos = {
                "paper_id": paper_id,
                "symbol": sym,
                "side": "long",
                "entry_ts": record["ts_utc"],
                "entry_px": entry_px,
                "entry_funding": float(df["funding_actual"].iloc[i]) if "funding_actual" in df.columns else 0.0,
                "size_coin": float(result.size_coin or 0),
                "notional_usd": notional,
                "stop_pct": policy["stop_pct"],
                "tp_pct": policy["tp_pct"],
                "max_hold_h": policy["max_hold_h"],
                "risk_usd": LIVE_RISK_USD,
                "decision_id": str(decision_id),
                "entry_oid": result.entry_oid,
                "tp_oid": result.tp_oid,
                "sl_oid": result.sl_oid,
            }
            current_open = _load_live_open_positions()
            # If we already have an open for this symbol, replace it
            current_open = [p for p in current_open if p.get("symbol") != sym]
            current_open.append(open_pos)
            _save_live_open_positions(current_open)

    _write_heartbeat("ok", f"syms={','.join(LIVE_SYMBOLS)} consec={state.get('consecutive_losses')}")


# -----------------------------------------------------------------------------
# Mode: audit
# -----------------------------------------------------------------------------

def mode_testnet_trading(arm: bool = False) -> None:
    """Route the fade signals to Hyperliquid testnet as real orders.

    Why this exists: the paper simulator answered "what would this strategy
    have made" with three assumptions the venue never agreed to -- it walked
    each symbol independently and so held more positions than
    max_open_positions allows, it filled every entry at the bar close with no
    spread or rejection, and it read a funding rate the venue had not yet
    published. Testnet replaces all three with an actual exchange response.

    Safety: refuses unless HYPERLIQUID_ENV=testnet, and points the SDK at
    TESTNET_API_URL explicitly rather than inheriting a default. It does not
    consult LIVE_TRADING_ENABLED -- no mainnet funds are involved, and gating
    testnet behind the mainnet flag would encourage flipping that flag to test.
    Writes to its own paths so testnet fills can never be mistaken for, or
    overwrite, mainnet records.
    """
    print("=== TESTNET funding_neg_fade: real orders, test funds ===")
    print(f"  symbols   = {TESTNET_SYMBOLS}")
    print(f"  bankroll  = ${TESTNET_BANKROLL_USD:.0f}   risk = ${TESTNET_RISK_USD:.2f}/trade")
    print(f"  max open  = {MAX_OPEN_POSITIONS}")
    print(f"  armed     = {arm}")
    print()

    # .env must be loaded before the guard reads HYPERLIQUID_ENV, or a
    # correctly-configured testnet box would look unset and be refused.
    try:
        from dotenv import load_dotenv
        load_dotenv(PROJECT_ROOT / ".env")
    except Exception as e:
        print(f"  REFUSED: could not load .env: {e}")
        return

    ok, reason = _testnet_guard_ok()
    if not ok:
        print(f"  REFUSED: {reason}")
        return
    print(f"  guard: {reason}")

    try:
        from dotenv import load_dotenv
        load_dotenv(PROJECT_ROOT / ".env")
        from eth_account import Account
        from hyperliquid.exchange import Exchange
        from hyperliquid.info import Info
        from hyperliquid.utils import constants
        pk = os.getenv("HYPERLIQUID_PRIVATE_KEY", "").strip()
        user = os.getenv("HYPERLIQUID_WALLET_ADDRESS", "").strip()
        if not pk.startswith("0x"):
            pk = "0x" + pk
        wallet = Account.from_key(pk)
        env_url = constants.TESTNET_API_URL
        # Belt and braces: if the SDK constant ever changes shape, fail loudly
        # rather than quietly transacting on mainnet.
        if "testnet" not in env_url:
            print(f"  REFUSED: resolved URL {env_url!r} is not a testnet endpoint")
            return
        info = Info(env_url, skip_ws=True)
        exchange = Exchange(wallet, env_url)
    except Exception as e:
        print(f"  REFUSED: could not build testnet SDK clients: {e}")
        return
    print(f"  endpoint: {env_url}")

    state = _load_live_state(TESTNET_STATE_PATH, bankroll=TESTNET_BANKROLL_USD)

    # Record anything that closed since the last tick before opening more, so
    # a freed slot is available to this tick's signals.
    try:
        closed = _detect_and_record_live_closes(info, user, state)
    except Exception as e:
        print(f"  close-detect failed: {e}")
        closed = 0
    if closed:
        print(f"  close-detect: recorded {closed} closed testnet position(s)")

    open_positions = _load_live_open_positions(TESTNET_OPEN_POSITIONS_PATH)
    print(f"  open now: {len(open_positions)}/{MAX_OPEN_POSITIONS}"
          f" {[o.get('symbol') for o in open_positions]}")

    om = OrderManagerFactory(exchange, info)
    TESTNET_ORDERS_PATH.parent.mkdir(parents=True, exist_ok=True)

    for sym in TESTNET_SYMBOLS:
        held = {o.get("symbol") for o in open_positions}
        if sym in held:
            print(f"  {sym}: already open, skipping")
            continue
        if len(open_positions) >= MAX_OPEN_POSITIONS:
            # The simulator's central bug was ignoring this. Report it rather
            # than skipping silently, so the cost of the cap stays visible.
            print(f"  {sym}: BLOCKED by max_open_positions={MAX_OPEN_POSITIONS}")
            _append_jsonl(TESTNET_ORDERS_PATH, {
                "ts_utc": pd.Timestamp.now(tz="UTC").isoformat(),
                "symbol": sym, "blocked_by": "max_open_positions",
            })
            continue
        if sym not in PER_ASSET_POLICY:
            print(f"  {sym}: no PER_ASSET_POLICY entry, skipping")
            continue
        try:
            loaded = load_hl_with_funding(sym)
            df = loaded[0] if isinstance(loaded, tuple) else loaded
        except Exception as e:
            print(f"  {sym}: load failed: {e}")
            continue

        policy = PER_ASSET_POLICY[sym]
        sig = signal_funding_neg_fade(df, funding_col="funding_actual",
                                      neg_threshold=NEG_THRESHOLD)
        sig_v = sig.to_numpy() if hasattr(sig, "to_numpy") else sig
        closes_arr = df["close"].values
        times = df.index
        idx = -1
        for i in range(1, len(df)):
            if sig_v[i] and not sig_v[i - 1] and closes_arr[i] > 0:
                idx = i
        if idx < 0:
            print(f"  {sym}: no fresh signal")
            continue
        # Only act on a signal from the most recent closed bar. An older one
        # has already been priced away, and firing it now would be acting on
        # stale information -- the same class of error as the funding shift.
        age_h = (pd.Timestamp(times[-1]) - pd.Timestamp(times[idx])) / pd.Timedelta(hours=1)
        if age_h > 1:
            print(f"  {sym}: signal is {age_h:.0f}h stale, not acting")
            continue

        entry_px = float(closes_arr[idx])
        sl_px = entry_px * (1 - policy["stop_pct"])
        tp_px = entry_px * (1 + policy["tp_pct"])
        notional = TESTNET_RISK_USD / max(policy["stop_pct"], 1e-6)
        print(f"  {sym}: signal @ {times[idx]} entry={entry_px} sl={sl_px:.4f} "
              f"tp={tp_px:.4f} notional=${notional:.0f}")
        if not arm:
            print(f"  {sym}: DRY RUN (pass --arm-testnet to submit)")
            continue

        result = _submit_testnet_bracket(om, sym, times[idx], entry_px, sl_px,
                                         tp_px, notional)
        _append_jsonl(TESTNET_ORDERS_PATH, {
            "ts_utc": pd.Timestamp.now(tz="UTC").isoformat(),
            "symbol": sym,
            "intent": {"signal_ts": str(times[idx]), "side": "long",
                       "entry_px": entry_px, "sl_px": sl_px, "tp_px": tp_px,
                       "notional_usd": notional},
            "result": result,
        })
        if result.get("filled"):
            print(f"  {sym}: FILLED oid={result.get('entry_oid')} size={result.get('size_coin')}")
            open_positions.append({
                "paper_id": f"testnet-fnf-{sym}-{pd.Timestamp(times[idx]).strftime('%Y%m%d%H%M')}",
                "symbol": sym, "side": "long",
                "entry_ts": pd.Timestamp.now(tz="UTC").isoformat(),
                "entry_px": entry_px, "size_coin": result.get("size_coin"),
                "notional_usd": notional,
                "stop_pct": policy["stop_pct"], "tp_pct": policy["tp_pct"],
                "max_hold_h": policy["max_hold_h"], "risk_usd": TESTNET_RISK_USD,
                "entry_oid": result.get("entry_oid"),
            })
            _save_live_open_positions(open_positions, TESTNET_OPEN_POSITIONS_PATH)
        else:
            print(f"  {sym}: NOT FILLED status={result.get('status')} "
                  f"error={result.get('error')}")

    _save_live_state(state, TESTNET_STATE_PATH)
    print(f"\n  orders log: {TESTNET_ORDERS_PATH}")


def _append_jsonl(path, record: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(record, default=str) + "\n")


def OrderManagerFactory(exchange, info):
    """Build an OrderManager bound to testnet with the testnet bankroll."""
    from src.execution.order_manager import OrderManager
    return OrderManager(
        exchange=exchange, info=info,
        bankroll=TESTNET_BANKROLL_USD,
        risk_per_trade_pct=TESTNET_RISK_USD / TESTNET_BANKROLL_USD,
        env="testnet",
    )


def _submit_testnet_bracket(om, sym, signal_ts, entry_px, sl_px, tp_px, notional) -> dict:
    from src.execution.order_manager import BracketOrderIntent
    intent = BracketOrderIntent(
        signal_ts=signal_ts, symbol=sym, side="long",
        entry_px=entry_px, sl_px=sl_px, tp_px=tp_px,
        notional_usd=notional,
        reason=f"funding_neg_fade testnet {sym} signal {signal_ts}",
    )
    try:
        r = om.execute_bracket_intent(intent)
    except Exception as e:  # noqa: BLE001
        return {"filled": False, "status": "exception", "error": str(e)}
    return {
        "filled": r.filled, "status": r.status, "entry_oid": r.entry_oid,
        "tp_oid": r.tp_oid, "sl_oid": r.sl_oid, "size_coin": r.size_coin,
        "risk_verdict": str(r.risk_verdict), "error": r.error,
    }


def mode_audit() -> None:
    positions = load_existing_positions()
    if not positions:
        print("no positions recorded")
        return
    closed = [p for p in positions if p.get("status") == "closed"]
    open_pos = [p for p in positions if p.get("status") == "open"]
    print(f"=== paper funding_neg_fade audit ===")
    print(f"  total: {len(positions)}  closed: {len(closed)}  open: {len(open_pos)}")

    if closed:
        pnls = np.array([p.get("net_pnl_usd", 0) for p in closed])
        wins = pnls[pnls > 0]
        losses = pnls[pnls <= 0]
        cum = pnls.sum()
        pf = (wins.sum() / abs(losses.sum())) if len(losses) and losses.sum() != 0 else 999
        print(f"  cum PnL: ${cum:+.2f}  WR: {(len(wins)/len(pnls)*100):.1f}%  PF: {pf:.2f}")
        print(f"  avg win: ${wins.mean():+.2f}  avg loss: ${losses.mean():+.2f}  max win: ${wins.max():+.2f}  max loss: ${losses.min():+.2f}")

    by_sym: dict[str, list[dict]] = {}
    for p in closed:
        by_sym.setdefault(p.get("symbol", "?"), []).append(p)
    for sym, plist in sorted(by_sym.items()):
        spnls = np.array([p["net_pnl_usd"] for p in plist])
        swins = spnls[spnls > 0]
        slosses = spnls[spnls <= 0]
        pf = (swins.sum() / abs(slosses.sum())) if len(slosses) and slosses.sum() != 0 else 999
        print(f"  {sym:6s} ({PER_ASSET_POLICY[sym]['bucket']:9s}) n={len(plist):3d}  cum=${spnls.sum():+.2f}  WR={(len(swins)/len(spnls)*100):.1f}%  PF={pf:.2f}")

    by_reason: dict[str, int] = {}
    for p in closed:
        by_reason[p.get("exit_reason", "?")] = by_reason.get(p.get("exit_reason", "?"), 0) + 1
    print(f"  exits: {by_reason}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["analyze", "paper", "live", "live_trading", "testnet_trading", "audit", "kill_switch", "arm_live"], default="paper")
    ap.add_argument("--arm-testnet", action="store_true",
                    help="actually submit orders in testnet_trading mode "
                         "(without it the mode prints intents and stops)")
    ap.add_argument("--symbol", action="append", help="restrict to symbol (repeatable)")
    args = ap.parse_args()
    if args.mode == "analyze":
        mode_analyze()
    elif args.mode == "paper":
        mode_paper(args.symbol)
    elif args.mode == "live":
        mode_live(args.symbol)
    elif args.mode == "live_trading":
        mode_live_trading()
    elif args.mode == "testnet_trading":
        mode_testnet_trading(arm=args.arm_testnet)
    elif args.mode == "kill_switch":
        KILL_SWITCH_PATH.parent.mkdir(parents=True, exist_ok=True)
        KILL_SWITCH_PATH.touch()
        print(f"kill switch ACTIVATED: {KILL_SWITCH_PATH}")
        print("live mode will refuse on next tick. rm the file to resume.")
    elif args.mode == "arm_live":
        # Set LIVE_TRADING_ENABLED = True in this file (surgical edit)
        text = Path(__file__).read_text(encoding="utf-8")
        if "LIVE_TRADING_ENABLED = True" in text:
            print("LIVE_TRADING_ENABLED already True")
        else:
            new = text.replace("LIVE_TRADING_ENABLED = False", "LIVE_TRADING_ENABLED = True", 1)
            Path(__file__).write_text(new, encoding="utf-8")
            print("LIVE_TRADING_ENABLED flipped to True. Edit-and-restart required to take effect in this process; next cron tick will use the new value.")
    elif args.mode == "audit":
        mode_audit()


if __name__ == "__main__":
    main()
