"""
HyphyLiquid - Testnet auth setup wizard.

One-shot script: prompts for wallet creds IN THE TERMINAL (never chat),
writes them to .env with restricted permissions, then runs the testnet
auth spike to prove the connection works end-to-end.

Usage:
    .\\venv\\Scripts\\python.exe scripts\\setup_testnet_auth.py

Pre-requisites:
    1. Get a wallet (any Ethereum address, e.g. from MetaMask)
    2. Export the PRIVATE KEY (0x... 64 hex chars) from your wallet
       (MetaMask: Account Details > Export Private Key)
    3. Get test USDC: https://app.hyperliquid-testnet.xyz/drip

The private key is never echoed, never logged, and never sent anywhere
except the .env file on your machine (which is gitignored).
"""
import getpass
import os
import sys
import stat
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


def _set_windows_acl(path: Path) -> None:
    """On Windows, restrict .env to current user only. Best-effort."""
    if sys.platform != "win32":
        return
    try:
        import subprocess
        # deny read for everyone except current user (best effort)
        username = os.environ.get("USERNAME", "")
        if username:
            subprocess.run(
                ["icacls", str(path), "/inheritance:r",
                 f"/grant:r", f"{username}:(R,W)",
                 "/deny", "Everyone:(R,W)"],
                check=False, capture_output=True,
            )
    except Exception:
        pass


def _derive_address(private_key: str):
    from eth_account import Account
    pk = private_key.strip()
    if not pk.startswith("0x"):
        pk = "0x" + pk
    try:
        return Account.from_key(pk).address
    except Exception as e:
        raise ValueError(f"Could not derive address from key: {e}")


def _check_eth_account():
    try:
        import eth_account  # noqa
    except ImportError:
        print("eth-account not installed.")
        print("  Add to requirements.txt and: pip install -r requirements.txt")
        sys.exit(1)


def main() -> int:
    print("=" * 70)
    print("HyphyLiquid - Testnet Auth Setup")
    print("=" * 70)
    print()
    print("This script will:")
    print("  1. Prompt for your testnet wallet address and private key")
    print("  2. Validate the key derives to the address")
    print("  3. Write them to .env (gitignored, restricted perms)")
    print("  4. Run the testnet auth spike (place + cancel a tiny order)")
    print()
    print("  Testnet USDC faucet: https://app.hyperliquid-testnet.xyz/drip")
    print()
    print("=" * 70)
    print()

    _check_eth_account()

    # Check existing .env
    env_path = PROJECT_ROOT / ".env"
    if env_path.exists():
        from dotenv import load_dotenv
        load_dotenv(env_path)
        existing_addr = os.getenv("HYPERLIQUID_WALLET_ADDRESS", "")
        existing_env = os.getenv("HYPERLIQUID_ENV", "")
        if existing_addr:
            print(f"Existing .env found:")
            print(f"  address: {existing_addr[:10]}...{existing_addr[-6:]}")
            print(f"  env: {existing_env or '(unset)'}")
            print()
            ans = input("Overwrite? (yes/no) [no]: ").strip().lower()
            if ans not in ("yes", "y"):
                print("Keeping existing .env, just running the auth spike...")
                print()
                _run_auth_spike()
                return 0

    # Prompt for credentials
    print("Enter your testnet wallet ADDRESS (0x... 42 hex chars):")
    addr = input("> ").strip()
    if not addr.startswith("0x") or len(addr) != 42:
        print(f"ERROR: address must start with 0x and be 42 chars, got {len(addr)} chars")
        return 1

    print()
    print("Enter your testnet wallet PRIVATE KEY (input is hidden):")
    print("  MetaMask: Account Details > Export Private Key")
    pk = getpass.getpass("> ").strip()

    if not pk:
        print("ERROR: empty private key")
        return 1
    if not pk.startswith("0x"):
        pk = "0x" + pk

    # Validate
    try:
        derived = _derive_address(pk)
    except ValueError as e:
        print(f"ERROR: {e}")
        return 1

    if derived.lower() != addr.lower():
        print(f"ERROR: private key does not derive to the given address.")
        print(f"  Given address:     {addr}")
        print(f"  Derived from key:  {derived}")
        print("  Double-check you exported the right key for this address.")
        return 1
    print()
    print(f"Key validated. Address: {addr}")
    print()

    # Write .env
    env_path = PROJECT_ROOT / ".env"
    content = (
        "# HyphyLiquid .env - generated by setup_testnet_auth.py\n"
        "# DO NOT COMMIT. .gitignore excludes this file.\n"
        "\n"
        "HYPERLIQUID_WALLET_ADDRESS=" + addr + "\n"
        "HYPERLIQUID_PRIVATE_KEY=" + pk + "\n"
        "HYPERLIQUID_ENV=testnet\n"
        "\n"
        "# Risk defaults (overridable; config/settings.yaml is source of truth)\n"
        "HYPERLIQUID_BANKROLL=1000\n"
        "HYPERLIQUID_MAX_LEVERAGE=10\n"
        "HYPERLIQUID_MAX_RISK_PCT=0.01\n"
        "HYPERLIQUID_DAILY_LOSS_LIMIT_PCT=0.03\n"
    )
    env_path.write_text(content, encoding="utf-8")

    # Restrict perms
    try:
        os.chmod(env_path, stat.S_IRUSR | stat.S_IWUSR)  # 0600 on Unix
    except Exception:
        pass
    _set_windows_acl(env_path)
    print(f"Wrote {env_path} (chmod 0600 / restricted ACL)")
    print()

    # Run the auth spike
    _run_auth_spike()
    return 0


def _run_auth_spike() -> None:
    """Run the testnet auth spike in-process."""
    import subprocess
    result = subprocess.run(
        [sys.executable, str(PROJECT_ROOT / "scripts" / "testnet_auth_spike.py")],
        cwd=str(PROJECT_ROOT),
    )
    if result.returncode != 0:
        print(f"\nAuth spike exited with code {result.returncode}")


if __name__ == "__main__":
    sys.exit(main())
